     - name: Set prompt
       ansible.builtin.shell: set-prompt {{ app-name}}- {{ env }}

     - name: Disable nginx modules first
       ansible.builtin.shell: dnf module disable nginx -y
    
     - name: Enable nginx modules
       ansible.builtin.shell: dnf module enable nginx:1.24 -y

     - name: Install nginx on frontend
       ansible.builtin.dnf:
         name: nginx
         state: installed


     - name: Recursively remove directory
       ansible.builtin.file:
         path: /usr/share/nginx/html
         state: absent
     
     - name:  create html directory
       ansible.builtin.file:
         path: /usr/share/nginx/html
         state: directory    

     - name: Copy nginx.conf file to web root
       ansible.builtin.template:
         src: nginx.conf
         dest: /etc/nginx/nginx.conf


     - name: Download and Extract frontend-v3.zip into /usr/share/nginx/html
       ansible.builtin.unarchive:
       src:   https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
       dest: /usr/share/nginx/html
       remote_src: yes

#     - name: Download frontend-v3.zip
#       ansible.builtin.get_url:
#         url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#         dest: /tmp/frontend.zip
#
#     - name: Extract frontend-v3.zip into /usr/share/nginx/html
#       ansible.builtin.unarchive:
#         src:  /tmp/frontend.zip
#         dest: /usr/share/nginx/html
#         remote_src: yes      # remote_src: yes  
   

     - name: Start the service
       ansible.builtin.service:
         name: nginx
         state: restarted
         enabled: yes
#ansible-playbook -i 172.31.38.240, -e ansible_user=ec2-user -e ansible_password=DevOps321 frontend.yml -e env=dev
#
#
#env=dev variable is defined in nginx.conf file like below:
#
#
#        location /api/catalogue/ { proxy_pass http://catalogue-{{ env }}.rdevopsb81.online:8080/; }
#        location /api/user/ { proxy_pass http://user-{{ env }}.rdevopsb81.online:8080/; }
#        location /api/cart/ { proxy_pass http://cart-{{ env }}.rdevopsb81.online:8080/; }
#        location /api/shipping/ { proxy_pass http://shipping-{{ env }}.rdevopsb81.online:8080/; }
#        location /api/payment/ { proxy_pass http://payment-{{ env }}.rdevopsb81.online:8080/; }


# command to run is 
# git pull; ansible-playbook -i frontend-dev.devopspractice.info, -e ansible_user=ec2-user -e ansible_password=DevOps321 -e env=dev -e app_name=frontend frontend.yml
