     - name: Copy file to web root
       ansible.builtin.template:
         src: "{{ app_name}}.service"
         dest: /etc/systemd/system/{{ app-name}}.service
     
     - name: Start the service
       ansible.builtin.systemd_service:
         name: "{{ app-name}}.service"
         state: restarted
         enabled: yes
         deaemon_reload: yes

     - name: Load App Prerequisites
       ansible.builtin.include_tasks:
          file: systemd_setup.yml